services:
  STACK_PLACEHOLDER-app:
    image: IMAGE_PLACEHOLDER
    environment:
      - PORT=PORT_PLACEHOLDER
##ENVS:app##
    networks:
      - caddy
    deploy:
      replicas: 1
      labels:
        caddy: HOST_PLACEHOLDER
        caddy.tls: TLS_PLACEHOLDER
        caddy.reverse_proxy: "{{upstreams PORT_PLACEHOLDER}}"

networks:
  caddy:
    external: true
